-- MySQL Script generated by MySQL Workbench
-- Thu Jan 26 14:14:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT NOT NULL,
  `parent` INT NULL DEFAULT 0,
  `name` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `id` INT NOT NULL,
  `country` TEXT NULL,
  `city` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`currency` ;

CREATE TABLE IF NOT EXISTS `mydb`.`currency` (
  `id` INT NOT NULL,
  `code` VARCHAR(8) NULL,
  `symbol` VARCHAR(45) NULL,
  `symbol_native` VARCHAR(45) NULL,
  `name` TEXT NULL,
  `name_plural` TEXT NULL,
  `decimals` INT NULL,
  `rounding` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`campaign` ;

CREATE TABLE IF NOT EXISTS `mydb`.`campaign` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `title` TEXT NULL,
  `type` TEXT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `funding_goal` DECIMAL(36,2) NULL,
  `recipient` TEXT NULL,
  `category_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_campaigns_category_idx` (`category_id` ASC),
  INDEX `fk_campaigns_location1_idx` (`location_id` ASC),
  INDEX `fk_campaigns_currency1_idx` (`currency_id` ASC),
  CONSTRAINT `fk_campaigns_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campaigns_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campaigns_currency1`
    FOREIGN KEY (`currency_id`)
    REFERENCES `mydb`.`currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`media` ;

CREATE TABLE IF NOT EXISTS `mydb`.`media` (
  `id` INT NOT NULL,
  `campaign_id` INT NOT NULL,
  `width` INT NULL,
  `height` INT NULL,
  `type` TEXT NULL,
  `url` TEXT NULL,
  `path` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_media_campaigns1_idx` (`campaign_id` ASC),
  CONSTRAINT `fk_media_campaigns1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `mydb`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`story`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`story` ;

CREATE TABLE IF NOT EXISTS `mydb`.`story` (
  `id` INT NOT NULL,
  `campaign_id` INT NOT NULL,
  `overview` TEXT NULL,
  `story` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_story_campaign1_idx` (`campaign_id` ASC),
  CONSTRAINT `fk_story_campaign1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `mydb`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reward`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reward` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reward` (
  `id` INT NOT NULL,
  `campaign_id` INT NOT NULL,
  `title` TEXT NULL,
  `amount` DECIMAL(36,2) NULL,
  `description` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rewards_campaign1_idx` (`campaign_id` ASC),
  CONSTRAINT `fk_rewards_campaign1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `mydb`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paymentinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`paymentinfo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`paymentinfo` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `name` TEXT NULL,
  `cardnumber` TEXT NULL,
  `cardtype` TEXT NULL,
  `cvv` VARCHAR(4) NULL,
  `expiry` DATETIME NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`backer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`backer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`backer` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `campaign_id` INT NOT NULL,
  `paymentinfo_id` INT NOT NULL,
  `reward_id` INT NOT NULL,
  `amount` DECIMAL(32,2) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_backers_reward1_idx` (`reward_id` ASC),
  INDEX `fk_backers_paymentinfo1_idx` (`paymentinfo_id` ASC),
  INDEX `fk_backer_campaign1_idx` (`campaign_id` ASC),
  CONSTRAINT `fk_backers_reward1`
    FOREIGN KEY (`reward_id`)
    REFERENCES `mydb`.`reward` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_backers_paymentinfo1`
    FOREIGN KEY (`paymentinfo_id`)
    REFERENCES `mydb`.`paymentinfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_backer_campaign1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `mydb`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
